# Windows profile startup
exec-once = $HOME/.local/bin/start-audio-session
exec-once = awww-daemon
exec-once = $HOME/.local/bin/windows-wallpaper-restore
exec-once = $HOME/.local/bin/windows-shell start
exec-once = playerctld
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
