font_family      JetBrainsMono Nerd Font Mono
font_size        12.5
bold_font        auto
italic_font      auto
bold_italic_font auto
adjust_line_height 110%
disable_ligatures never

cursor_shape beam
cursor_blink_interval 0.55
cursor_trail 3
cursor_trail_decay 0.08 0.22

background_opacity 0.86
dynamic_background_opacity yes
background_blur 32
confirm_os_window_close 0
scrollback_lines 10000
wheel_scroll_min_lines 1
enable_audio_bell no
hide_window_decorations yes
remember_window_size yes
initial_window_width 1040
initial_window_height 680
window_padding_width 13
window_margin_width 0
single_window_margin_width 0

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template " {index}: {title} "
active_tab_font_style bold
url_style curly
open_url_with default
shell_integration enabled

include ~/.config/kitty/windows11-colors.conf
