foreground #e7eef8
background #0b1019
selection_foreground #ffffff
selection_background #244d6b
cursor #60cdff
cursor_text_color #081018
url_color #60cdff
active_border_color #60cdff
inactive_border_color #263343
bell_border_color #ff99a4
active_tab_foreground #071018
active_tab_background #60cdff
inactive_tab_foreground #b9c5d3
inactive_tab_background #17202c
tab_bar_background #0b1019
color0 #101721
color8 #536477
color1 #ff7b86
color9 #ff99a4
color2 #6ccb8e
color10 #8be9a8
color3 #f3c96b
color11 #ffe28a
color4 #4ca6ff
color12 #60cdff
color5 #c58af9
color13 #d7a6ff
color6 #44d7cf
color14 #66eee5
color7 #c7d0dc
color15 #f4f8ff
